v0.3.3c: added sysctls and more color to --kdump

diff --git a/xsos b/xsos
--- a/xsos
+++ b/xsos
@@ -1,5 +1,5 @@
 #!/bin/bash
-# xsos v0.3.3b last mod 2013/12/04
+# xsos v0.3.3c last mod 2013/12/06
 # Latest version at <http://github.com/ryran/xsos>
 # RPM packages available at <http://people.redhat.com/rsawhill/rpms>
 # Copyright 2012, 2013 Ryan Sawhill Aroha <rsaw@redhat.com>
@@ -1136,7 +1136,7 @@ KDUMP() {
   
   # If the os module was called, grub config was already inspected; otherwise, we need to do it
   [[ -n $os ]] || _CHECK_GRUB "$1"
-  
+        
   # If running on localhost ....
   if [[ $1 == / ]]; then
     __rpm_check_kexec() {
@@ -1161,36 +1161,36 @@ KDUMP() {
   # If running on sosreport ....
   else
     __rpm_check_kexec() {
-      if [[ -r "$1"/installed-rpms ]]; then
-        grep -q kexec-tools "$1"/installed-rpms \
-          && awk '/kexec-tools/{print$1}' "$1"/installed-rpms \
+      if [[ -r "$sosroot"/installed-rpms ]]; then
+        grep -q kexec-tools "$sosroot"/installed-rpms \
+          && awk '/kexec-tools/{print$1}' "$sosroot"/installed-rpms \
           || echo -e "${c[Warn1]}package kexec-tools is not installed${c[0]}"
       else
-        echo -e "${c[Warn1]}missing '$1/installed-rpms'${c[0]}"
+        echo -e "${c[Warn1]}missing '$sosroot/installed-rpms'${c[0]}"
       fi
     }
     __svc_check_kdump() {
-      if [[ -r "$1"/chkconfig ]]; then
-        grep -q ^kdump "$1"/chkconfig \
-          && grep ^kdump "$1"/chkconfig | column -t \
+      if [[ -r "$sosroot"/chkconfig ]]; then
+        grep -q ^kdump "$sosroot"/chkconfig \
+          && grep ^kdump "$sosroot"/chkconfig | column -t \
           || echo -e "${c[Warn1]}kdump not present in chkconfig output${c[0]}"
       else
-        echo -e "${c[Warn1]}missing '$1/chkconfig'${c[0]}"
+        echo -e "${c[Warn1]}missing '$sosroot/chkconfig'${c[0]}"
       fi
     }
     __initrd_file_check() {
-      if [[ -r "$1"/sos_commands/bootloader/ls_-laR_.boot ]]; then
-        kdump_initrd=$(grep 'initrd-.*kdump.img$' "$1"/sos_commands/bootloader/ls_-laR_.boot) \
+      if [[ -r "$sosroot"/sos_commands/bootloader/ls_-laR_.boot ]]; then
+        kdump_initrd=$(grep 'initrd-.*kdump.img$' "$sosroot"/sos_commands/bootloader/ls_-laR_.boot) \
           && sed -r 's@^........... +[0-9]+ \w+ *\w+ *([0-9]+ .*)@\1@' <<<"$kdump_initrd" | sed -r 's,/+boot/,,' \
-          || echo -e "${c[Warn1]}missing '/boot/initrd-*kdump.img' according to '"$1"/sos_commands/bootloader/ls_-laR_.boot'${c[0]}"
+          || echo -e "${c[Warn1]}missing '/boot/initrd-*kdump.img' according to '$sosroot/sos_commands/bootloader/ls_-laR_.boot'${c[0]}"
       else
-        echo -e "${c[Warn1]}missing '$1/sos_commands/bootloader/ls_-laR_.boot'${c[0]}"
+        echo -e "${c[Warn1]}missing '$sosroot/sos_commands/bootloader/ls_-laR_.boot'${c[0]}"
       fi
     }
     __get_df_for_parent_fs_of_path() {
       local dfpath lastloop
       dfpath=$path
-      while [[ $(awk -vP=$dfpath '{if ($6==P) n+=1} END{if (n>=1) print 0; else print 255}'  "$1"/sos_commands/filesys/df_-al) -eq 255 ]]; do
+      while [[ $(awk -vP=$dfpath '{if ($6==P) n+=1} END{if (n>=1) print 0; else print 255}'  "$sosroot"/sos_commands/filesys/df_-al) -eq 255 ]]; do
         if [[ $lastloop == y ]]; then
           echo "DEBUG: This should never happen unless sos_commands/filesys/df_-al is missing an entry for '/'"
           return 2
@@ -1201,15 +1201,15 @@ KDUMP() {
           lastloop=y
         fi
       done
-      df_output=$(awk -vP=$dfpath '$6==P'  "$1"/sos_commands/filesys/df_-al)
+      df_output=$(awk -vP=$dfpath '$6==P'  "$sosroot"/sos_commands/filesys/df_-al)
     }
   fi
   
   # A couple functions that work regardless of localhost/sosreport
   __get_crashkernel_proc_cmdline() {
     local out
-    if [[ -r "$1"/proc/cmdline ]]; then
-      out=$(egrep -o 'crashkernel=[[:graph:]]+' "$1"/proc/cmdline)
+    if [[ -r "$sosroot"/proc/cmdline ]]; then
+      out=$(egrep -o 'crashkernel=[[:graph:]]+' "$sosroot"/proc/cmdline)
     else
       out="${c[Warn1]}file missing${c[0]}"
     fi
@@ -1224,30 +1224,39 @@ KDUMP() {
     fi
     [[ -n $out ]] && echo -e "$out" || echo -e "${c[Warn1]}not present${c[0]}"
   }
+  __P() {
+    echo -e "$XSOS_INDENT_H2${c[H3]}${1} =  $(awk -vW="${c[Warn1]}" -vG="${c[green]}" '{ if ($1==0) print W 0; else print G $1 }' "$sosroot"/proc/sys/${1//.//} 2>/dev/null)${c[0]}"
+  }
+  __Pa() {
+    echo -e "$XSOS_INDENT_H2${c[H3]}${1} ${c[H4]}$2${c[H3]}=  $(awk -vW="${c[Warn1]}" -vG="${c[green]}" -vH0="${c[0]}" "$3" "$4" "$sosroot"/proc/sys/${1//.//} 2>/dev/null)${c[0]}"
+  }
   
   echo -e "${c[H1]}KDUMP CONFIG${c[0]}"
   echo -e "$XSOS_INDENT_H1${c[H2]}kexec-tools rpm version:${c[0]}"
-    __rpm_check_kexec "$1" | sed "s,^,$XSOS_INDENT_H2,"
+    __rpm_check_kexec | sed "s,^,$XSOS_INDENT_H2,"
   echo -e "$XSOS_INDENT_H1${c[H2]}Service enablement:${c[0]}"
-    __svc_check_kdump "$1" | sed "s,^,$XSOS_INDENT_H2,"
+    __svc_check_kdump | awk -vH0="${c[0]}" -vgreen="${c[green]}" -vwarn="${c[Warn1]}" '
+            { for (i=2; i<6; i++) { gsub(i ":on", i ":" green "on" H0); gsub(i ":off", i ":" warn "off" H0) }
+              print
+            }' | sed "s,^,$XSOS_INDENT_H2,"
   echo -e "$XSOS_INDENT_H1${c[H2]}kdump initrd.img:${c[0]}"
-    __initrd_file_check "$1" | awk '{ print gensub(/^([0-9]+) *([[:upper:]][[:lower:]]+) *([0-9]{1,2}) *([0-9]{4}) *(initrd.*)$/, "\\1  \\2 \\3 \\4  \\5", 1) }' | sed "s,^,$XSOS_INDENT_H2,"
+    __initrd_file_check | awk '{ print gensub(/^([0-9]+) *([[:upper:]][[:lower:]]+) *([0-9]{1,2}) *([0-9]{4}) *(initrd.*)$/, "\\1  \\2 \\3 \\4  \\5", 1) }' | sed "s,^,$XSOS_INDENT_H2,"
     # The extra awk command above reformats spacing in the ls -l output
   echo -e "$XSOS_INDENT_H1${c[H2]}Memory reservation:${c[0]}"
     grep -qsw rescue "$1/proc/cmdline" && echo -e "$XSOS_INDENT_H1 ${c[Warn2]}(Rescue mode detected)${c[0]}"
-    echo -e "$XSOS_INDENT_H2${c[H3]}/proc/cmdline {${c[0]} $(__get_crashkernel_proc_cmdline "$1") ${c[H3]}}${c[0]}"
-    echo -e "$XSOS_INDENT_H2${c[H3]}GRUB default  {${c[0]} $(__get_crashkernel_grub_cmdline "$1") ${c[H3]}}${c[0]}"
+    echo -e "$XSOS_INDENT_H2${c[H3]}/proc/cmdline {${c[0]} $(__get_crashkernel_proc_cmdline) ${c[H3]}}${c[0]}"
+    echo -e "$XSOS_INDENT_H2${c[H3]}GRUB default  {${c[0]} $(__get_crashkernel_grub_cmdline) ${c[H3]}}${c[0]}"
   echo -e "$XSOS_INDENT_H1${c[H2]}kdump.conf:${c[0]}"
   
-    if [[ -r "$1"/etc/kdump.conf ]]; then
-      kdump_cfg=$(egrep -v '^[[:space:]]*$|^#' "$1"/etc/kdump.conf)
+    if [[ -r "$sosroot"/etc/kdump.conf ]]; then
+      kdump_cfg=$(egrep -v '^[[:space:]]*$|^#' "$sosroot"/etc/kdump.conf)
       if [[ -n $kdump_cfg ]]; then
         sed "s,^,$XSOS_INDENT_H2," <<<"$kdump_cfg"
-        path=$(awk '/^path / {print$2}' "$1"/etc/kdump.conf)
+        path=$(awk '/^path / {print$2}' "$sosroot"/etc/kdump.conf)
         [[ -z $path ]] && path=/var/crash
         
         for target in raw nfs ssh ext2 ext3 ext4 btrfs xfs; do
-          if grep -q ^$target "$1"/etc/kdump.conf; then
+          if grep -q ^$target "$sosroot"/etc/kdump.conf; then
             path=
             break
           fi
@@ -1259,20 +1268,16 @@ KDUMP() {
       fi
       
       if [[ -n $path ]]; then
-        __get_df_for_parent_fs_of_path "$1"
+        __get_df_for_parent_fs_of_path
         if [[ -n $df_output ]]; then
           echo -e "$XSOS_INDENT_H1${c[H2]}kdump.conf \"path\" available space:${c[0]}"
-          MemTotal=$(awk '/^MemTotal/{printf "%.2f\n", $2/1024/1024}' "$1"/proc/meminfo)
+          MemTotal=$(awk '/^MemTotal/{printf "%.2f\n", $2/1024/1024}' "$sosroot"/proc/meminfo)
           PathAvailableSpace=$(awk '{printf "%.2f\n", $4/1024/1024}' <<<"$df_output")
-          ColorAvailable=$(awk -vP=$path -vMemtotal=$(awk /MemTotal/{print\$2} "$1"/proc/meminfo) '
-            {
-              if ($4 > Memtotal) print "green"
-              else if ($4 == Memtotal) print "orange"
-              else if ($4 < Memtotal) print "red"
-            }
-          '  <<<"$df_output")
+          ColorAvailable=$(awk -vP=$path -vMemtotal=$(awk /MemTotal/{print\$2} "$sosroot"/proc/meminfo) '
+                            { if ($4 > Memtotal) print "green"; else print "orange" }
+                           '  <<<"$df_output")
           echo -e "$XSOS_INDENT_H2${c[H3]}System MemTotal (uncompressed core size) {${c[0]} $MemTotal GiB ${c[H3]}}${c[0]}"
-          echo -e "$XSOS_INDENT_H2${c[H3]}Available free space on target path fs   {${c[0]} ${c[$ColorAvailable]}$PathAvailableSpace GiB ${c[H3]}}${c[0]}  (path=$path; fs=$(awk '{print$6}' <<<"$df_output"))"
+          echo -e "$XSOS_INDENT_H2${c[H3]}Available free space on target path's fs {${c[0]} ${c[$ColorAvailable]}$PathAvailableSpace GiB ${c[H3]}}${c[0]}  (fs=$(awk '{print$6}' <<<"$df_output"))"
         else
           echo "DEBUG: no df_output .. shouldn't happen"
         fi
@@ -1281,6 +1286,23 @@ KDUMP() {
     else
       echo -e "$XSOS_INDENT_H2${c[Warn1]}missing '$1/etc/kdump.conf'${c[0]}"
     fi
+
+  echo -e "$XSOS_INDENT_H1${c[H2]}Panic sysctls:${c[0]}"
+  if grep -qsw rescue "$sosroot/proc/cmdline"; then
+    echo -e "$XSOS_INDENT_H1${c[Warn2]}  WARNING: RESCUE MODE DETECTED${c[0]}"
+    echo -e "$XSOS_INDENT_H1${c[Warn1]}  sysctls below reflect rescue env; inspect sysctl.conf manually${c[0]}"
+  fi
+  __Pa kernel.panic "[secs] "  '{if ($1>0) printf "%s%s%s  (secs til autoreboot after panic)", W, $1, H0; else printf "%s0%s  (no autoreboot on panic)", G, H0}'
+  __P kernel.hung_task_panic
+  __P kernel.panic_on_oops
+  __P kernel.panic_on_io_nmi
+  __P kernel.panic_on_unrecovered_nmi
+  __P kernel.panic_on_stackoverflow
+  __P kernel.softlockup_panic 
+  __P kernel.unknown_nmi_panic
+  __P kernel.nmi_watchdog
+  __Pa vm.panic_on_oom "[0-2] "  '{if ($1==0) printf "%s0%s  (no panic)", W, H0; else if ($1==1) printf "%s1%s  (no panic if OOM-triggering task limited by mbind/cpuset)", G, H0; else if ($1==2) printf "%s2%s  (always panic)", G, H0}'
+  
   echo -en $XSOS_HEADING_SEPARATOR
 }
 
@@ -2432,6 +2454,7 @@ SYSCTL() {
   __P kernel.panic_on_io_nmi "[bool] "
   __P kernel.panic_on_unrecovered_nmi "[bool] "
   __P kernel.unknown_nmi_panic "[bool] "
+  __P kernel.panic_on_stackoverflow "[bool] "
   __P kernel.softlockup_panic "[bool] "
   __P kernel.softlockup_thresh "[secs] "
   __P kernel.pid_max
