v0.4.3: rhel7 fixes for --kdump & /proc/cmdline

diff --git a/xsos b/xsos
--- a/xsos
+++ b/xsos
@@ -1,5 +1,5 @@
 #!/bin/bash
-# xsos v0.4.2 last mod 2014/06/13
+# xsos v0.4.3 last mod 2014/06/22
 # Latest version at <http://github.com/ryran/xsos>
 # RPM packages available at <http://people.redhat.com/rsawhill/rpms>
 # Copyright 2012, 2013, 2014 Ryan Sawhill Aroha <rsaw@redhat.com>
@@ -1067,9 +1067,8 @@ OSINFO() {
   grep -qsw rescue "$1/proc/cmdline" &&
     echo -e "     ${c[Warn1]}(Rescue mode detected)${c[0]}"
   if [[ -r $1/proc/cmdline ]]; then
-    [[ $XSOS_SCRUB_IP_HN == y ]] \
-      && proc_cmdline=$(sed "s/${hostname%%.*}/HOSTNAME/g" "$1"/proc/cmdline) \
-      || proc_cmdline=$(<"$1"/proc/cmdline)
+    proc_cmdline=$(sed -r 's,^BOOT_IMAGE=/[[:graph:]]+ ,,' "$1"/proc/cmdline)
+    [[ $XSOS_SCRUB_IP_HN == y ]] && proc_cmdline=$(sed "s/${hostname%%.*}/HOSTNAME/g" <<<"$proc_cmdline")
     fold -sw$XSOS_FOLD_WIDTH <<<"$proc_cmdline" 2>/dev/null | sed -e "s,^,$XSOS_INDENT_H3,"
   else
     echo -e "$XSOS_INDENT_H3${c[Warn1]}unknown${c[0]}"
@@ -1165,7 +1164,7 @@ OSINFO() {
 
 KDUMP() {
   # Local vars
-  local kexec_tools_vers kdump_initrd path kdump_cfg target MemTotal PathAvailableSpace ColorAvailable
+  local kexec_tools_vers kdump_initrd path kdump_cfg target MemTotal PathAvailableSpace ColorAvailable lsbootfile
   
   # If the os module was called, grub config was already inspected; otherwise, we need to do it
   [[ -n $os ]] || _CHECK_GRUB "$1"
@@ -1178,14 +1177,34 @@ KDUMP() {
         || echo -e "${c[Warn1]}$kexec_tools_vers${c[0]}"
     }
     __svc_check_kdump() {
-      chkconfig --list kdump &>/dev/null \
-        && chkconfig --list kdump | column -t \
-        || echo -e "${c[Warn1]}$(chkconfig --list kdump 2>&1)${c[0]}"
+      if command -v systemctl >/dev/null; then
+        if systemctl list-units --all | grep -qs kdump.service; then
+          systemctl list-units --all | awk 'NR==1 || /kdump.service/ { print $1, $2, $3, $4 }' | column -t | awk -vH0="${c[0]}" -vgreen="${c[green]}" -vwarn="${c[Warn1]}" '
+            { gsub("not-found|failed", warn "&" H0)
+              gsub("active", green "&" H0)
+              print
+            }'
+        else
+          echo -e "${c[Warn1]}Unit kdump.service not-found (Reason: No such file or directory)${c[0]}"
+        fi
+      else
+        if chkconfig --list kdump &>/dev/null; then
+          chkconfig --list kdump | column -t | awk -vH0="${c[0]}" -vgreen="${c[green]}" -vwarn="${c[Warn1]}" '
+            { for (i=3; i<6; i++) {
+                gsub(i ":on", i ":" green "on" H0)
+                gsub(i ":off", i ":" warn "off" H0)
+              }
+              print
+            }'
+        else
+          echo -e "${c[Warn1]}$(chkconfig --list kdump 2>&1)${c[0]}"
+        fi
+      fi
     }
     __initrd_file_check() {
-      ls /boot/initrd-*kdump.img &>/dev/null \
-        && ls -l /boot/initrd-*kdump.img | sed -r 's@^........... +[0-9]+ \w+ *\w+ *([0-9]+ .*)@\1@' | sed -r 's,/+boot/,,' \
-        || echo -e "${c[Warn1]}missing '/boot/initrd-*kdump.img'${c[0]}"
+      ls /boot/initr*kdump.img &>/dev/null \
+        && ls -l /boot/initr*kdump.img | sed -r 's@^........... +[0-9]+ \w+ *\w+ *([0-9]+ .*)@\1@' | sed -r 's,/+boot/,,' \
+        || echo -e "${c[Warn1]}missing '/boot/initr*kdump.img'${c[0]}"
     }
     __get_df_for_parent_fs_of_path() {
       df_output=$(df "$path" | awk '{if (NF==1) {dev=$1; getline; print dev $0} else if (NR==2) print}')
@@ -1204,27 +1223,49 @@ KDUMP() {
       fi
     }
     __svc_check_kdump() {
-      if [[ -r "$sosroot"/chkconfig ]]; then
-        grep -q ^kdump "$sosroot"/chkconfig \
-          && grep ^kdump "$sosroot"/chkconfig | column -t \
-          || echo -e "${c[Warn1]}kdump not present in chkconfig output${c[0]}"
+      if [[ -r "$sosroot"/sos_commands/systemd/systemctl_list-units_--all ]]; then
+        if grep -qs kdump.service "$sosroot"/sos_commands/systemd/systemctl_list-units_--all; then
+          awk 'NR==1 || /kdump.service/ { print $1, $2, $3, $4 }' "$sosroot"/sos_commands/systemd/systemctl_list-units_--all | column -t | awk -vH0="${c[0]}" -vgreen="${c[green]}" -vwarn="${c[Warn1]}" '
+            { gsub("not-found|failed", warn "&" H0)
+              gsub("active", green "&" H0)
+              print
+            }'
+        else
+          echo -e "${c[Warn1]}Unit kdump.service not-found (Reason: No such file or directory)${c[0]}"
+        fi
       else
-        echo -e "${c[Warn1]}missing '$sosroot/chkconfig'${c[0]}"
+        if [[ -r "$sosroot"/chkconfig ]]; then
+          if grep -q ^kdump "$sosroot"/chkconfig; then
+            grep ^kdump "$sosroot"/chkconfig | column -t | awk -vH0="${c[0]}" -vgreen="${c[green]}" -vwarn="${c[Warn1]}" '
+              { for (i=3; i<6; i++) {
+                  gsub(i ":on", i ":" green "on" H0)
+                  gsub(i ":off", i ":" warn "off" H0)
+                }
+                print
+              }'
+          else
+            echo -e "${c[Warn1]}kdump not present in chkconfig output${c[0]}"
+          fi
+        else
+          echo -e "${c[Warn1]}missing '$sosroot/chkconfig'${c[0]}"
+        fi
       fi
     }
     __initrd_file_check() {
-      if [[ -r "$sosroot"/sos_commands/bootloader/ls_-laR_.boot ]]; then
-        kdump_initrd=$(grep 'initrd-.*kdump.img$' "$sosroot"/sos_commands/bootloader/ls_-laR_.boot) \
-          && sed -r 's@^........... +[0-9]+ \w+ *\w+ *([0-9]+ .*)@\1@' <<<"$kdump_initrd" | sed -r 's,/+boot/,,' \
-          || echo -e "${c[Warn1]}missing '/boot/initrd-*kdump.img' according to '$sosroot/sos_commands/bootloader/ls_-laR_.boot'${c[0]}"
+      [[ -r "$sosroot"/sos_commands/bootloader/ls_-laR_.boot ]] && lsbootfile="$sosroot"/sos_commands/bootloader/ls_-laR_.boot
+      [[ -r "$sosroot"/sos_commands/boot/ls_-lanR_.boot ]] && lsbootfile="$sosroot"/sos_commands/boot/ls_-lanR_.boot
+      if [[ -z $lsbootfile ]]; then
+        echo -e "${c[Warn1]}missing '$sosroot/sos_commands/bootloader/ls_-laR_.boot' & '$sosroot/sos_commands/boot/ls_-lanR_.boot'${c[0]}"
       else
-        echo -e "${c[Warn1]}missing '$sosroot/sos_commands/bootloader/ls_-laR_.boot'${c[0]}"
+        kdump_initrd=$(grep 'initr.*kdump.img$' "$lsbootfile") \
+          && sed -r 's@^........... +[0-9]+ \w+ *\w+ *([0-9]+ .*)@\1@' <<<"$kdump_initrd" | sed -r 's,/+boot/,,' \
+          || echo -e "${c[Warn1]}missing '/boot/initr*kdump.img' according to '$lsbootfile'${c[0]}"
       fi
     }
     __get_df_for_parent_fs_of_path() {
       local dfpath lastloop
       dfpath=$path
-      while [[ $(awk -vP=$dfpath '{if ($6==P || $5==P) n+=1} END{if (n>0) print 0; else print 255}'  "$sosroot"/sos_commands/filesys/df_-al) -eq 255 ]]; do
+      while [[ $(grep -v ^rootfs "$sosroot"/sos_commands/filesys/df_-al | awk -vP=$dfpath '{if ($6==P || $5==P) n+=1} END{if (n>0) print 0; else print 255}') -eq 255 ]]; do
         if [[ $lastloop == y ]]; then
           echo "DEBUG: This should never happen unless sos_commands/filesys/df_-al is missing an entry for '/'"
           return 2
@@ -1235,7 +1276,7 @@ KDUMP() {
           lastloop=y
         fi
       done
-      df_output=$(awk -vP=$dfpath '{if (NF==6 && $6==P) print; else if (NF==1) {dev=$1; getline; if ($5==P) print dev $0} }'  "$sosroot"/sos_commands/filesys/df_-al)
+      df_output=$(grep -v ^rootfs "$sosroot"/sos_commands/filesys/df_-al | awk -vP=$dfpath '{if (NF==6 && $6==P) print; else if (NF==1) {dev=$1; getline; if ($5==P) print dev $0} }')
     }
   fi
   
@@ -1269,11 +1310,8 @@ KDUMP() {
   echo -e "$XSOS_INDENT_H1${c[H2]}kexec-tools rpm version:${c[0]}"
     __rpm_check_kexec | sed "s,^,$XSOS_INDENT_H2,"
   echo -e "$XSOS_INDENT_H1${c[H2]}Service enablement:${c[0]}"
-    __svc_check_kdump | awk -vH0="${c[0]}" -vgreen="${c[green]}" -vwarn="${c[Warn1]}" '
-            { for (i=3; i<6; i++) { gsub(i ":on", i ":" green "on" H0); gsub(i ":off", i ":" warn "off" H0) }
-              print
-            }' | sed "s,^,$XSOS_INDENT_H2,"
-  echo -e "$XSOS_INDENT_H1${c[H2]}kdump initrd.img:${c[0]}"
+    __svc_check_kdump | sed "s,^,$XSOS_INDENT_H2,"
+  echo -e "$XSOS_INDENT_H1${c[H2]}kdump initrd/initramfs:${c[0]}"
     __initrd_file_check | awk '{ print gensub(/^([0-9]+) *([[:upper:]][[:lower:]]+) *([0-9]{1,2}) *([0-9]{4}) *(initrd.*)$/, "\\1  \\2 \\3 \\4  \\5", 1) }' | sed "s,^,$XSOS_INDENT_H2,"
     # The extra awk command above reformats spacing in the ls -l output
   echo -e "$XSOS_INDENT_H1${c[H2]}Memory reservation:${c[0]}"
